version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
  contacts-api:
    build:
      context: ./contacts-api
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      - db
#    volumes:
#      - ./contacts-api/app/dist:/home/node/dist
#      - ./contacts-api/app/node_modules:/home/node/node_modules